add_newline = false

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[➜](bold red)"

[directory]
truncation_length = 1
style = "bold fg:cyan"

[git_branch]
symbol = " "

[line_break]
disabled = true
